apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jlin4tut6-java-springboot
  janus-idp.io/tekton: jlin4tut6-java-springboot
  backstage.io/kubernetes-id: jlin4tut6-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jlin4tut6-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
